security:
    password_hashers:
        App\Entity\gestion_user\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\gestion_user\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
                enable_csrf: true
                success_handler: App\Security\LoginSuccessHandler

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /

            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/admin/evenements, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/employe, roles: ROLE_EMPLOY }
        - { path: ^/client/evenements, roles: ROLE_CLIENT }
        - { path: ^/sponsor/demandes, roles: ROLE_SPONSOR }
