<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAmJPaGs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAmJPaGs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAmJPaGs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAmJPaGs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAmJPaGs\App_KernelDevDebugContainer([
    'container.build_hash' => 'AmJPaGs',
    'container.build_id' => '1340253f',
    'container.build_time' => 1745490945,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAmJPaGs');
